kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  namespace: demo
  labels:
    app: redis
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    requirepass demo
    pidfile /run/redis/redis-6379.pid